[package]
name = "beat-watcher"
version = "0.1.0"
authors = ["miguel <miguel@human.x.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpython = "0.4"
